import '@/base/styles/custom-font.css';
import '@/base/styles/globals.css';
import {Footer, Header} from '@/widgets';
import type {Metadata} from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <main className='flex min-h-screen flex-col items-center justify-between'>
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
